title: Apple
subtitle: This is how I do it:) 
description: >- # this means to ignore newlines until "baseurl:"
  devlopr-jekyll is a beautiful Jekyll Theme Built For Developers, which is optimized for speed and readability.

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# Navigation
urls:
    - text: Home
      url: /
    - text: About
      url: /about
    - text: Blog
      url: /blog
    - text: Gallery
      url: /gallery
    - text: Shop
      url : /shop
    - text: Contact
      url : /contact


# Edit Author details (For multi authors check _data/authors.yml)

author_logo: appleavatar.jpg
author: Wai Teng
author_bio: Hi, my name is Wai Teng. Baby steps in my tech journey~ 
author_email: "applewongwt@gmail.com"
author_location: Singapore
# author_website_url: "https://sujaykundu.com"
typewrite-text: Let's help each other get better!
hero_cover_img: galaxy.jpg # replace this for changing homepage cover (eg. try cover.jpeg). Image should be in /assets/img

# Experiences
author_work_experiences:
            - company_name: The Software Practice Pte Ltd
              company_logo: TSP logo.png
              company_url: https://thesoftwarepractice.com/
              designation: Business Analyst/ Project Management
              description: o	Key role in managing the development of government projects, <br>
                            risk management, collaboration with client stakeholders, <br>
                            develop user stories, functional specifications and acceptance criteria. <br>
                            o	Exposure to Azure and AWS Cloud Systems
              visibility: true
            - company_name: Neoasia Group
              company_logo: neoasia logo.png
              company_url: https://neoasiagroup.com/
              designation: Finance and Operations Intern
              description: Revamped SOPs and data analysis for financial reporting
              visibility: true
            - company_name: BMW Asia
              company_logo: BMW logo.png
              # company_url: 
              designation: Product and Technology Integration | Group IT APAC Intern
              description: Agile Working Model preparation, Data Analytics, JIRA
              visibility: true

# Education
author_education_details:
              - college_logo: ntu.png
                college_name: Nanyang Technological University
                # college_url: https://mit.org
                college_degree: Bachelors in Mathematical Sciences (Specialisation in Business Analytics)
                description: Bachelor of Science
                GPA: 4.10/5
                visibility: true
                
author_education_details:
              - college_logo: ntu.png
                college_name: Nanyang Technological University
                # college_url: https://mit.org
                college_degree: Bachelors in Mathematical Sciences (Specialisation in Business Analytics)
                description: Bachelor of Science
                GPA: 4.10/5
                visibility: true



# Projects
author_project_details:
              - project_thumbnail: sfa_logo_crop.png
                project_title: 1) Project for Singapore Food Agency (GCC) 
                project_description: Web Application for Laboratories, Inspection Bodies and Auditors to apply and attain certification for Recognition programmes 
                # project_url: https://www.sfa.gov.sg/food-information/recognition-programmes
                visibility: true


              - project_thumbnail: muis_crop.png
                project_title: 2) Project for Masjid Ugama Islam Singapura (GCC)
                project_description: Web Application for prospective pilgrims to register and manage their status from registration to performing haj <br> 
                                      https://www.muis.gov.sg/Haj/Services/Haj-Registration/MyHajSG
                # project_url: https://www.muis.gov.sg/Haj/Services/Haj-Registration/MyHajSG
                visibility: true


              - project_thumbnail: smrt.jpg
                project_title: 3)	Project for Singapore Mass Rapid Transit (Azure Cloud Services)
                project_description: | 
                                      Web Application for Station Staff to manage their <br>
                                        o	Manpower Rosters <br>
                                        o	Cash and Inventory <br>
                                        o	Fault Tracking/ Station Occurrences <br>
                                        o	Wayfinding and Announcements <br>
                                        asoms.smrt.com.sg
                # project_url: asoms.smrt.com.sg
                visibility: true

# social links
# twitter_username: johndoe
# github_username:  sujaykundu777
# facebook_username: johndoe
linkedin_username: wai-teng-wong
# behance_username: johndoe
instagram_username: waiteng_h2so4
# medium_username: johndoe
telegram_username: applewaiteng
# dribbble_username: johndoe
# flickr_username: johndoe

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
hyvor_talk_website_id: 476

# wakatime username (coding activity)
# wakatime_username: sujaykundu777

# mailchimp embedded form url (newsletter):
mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# contact form - (choose formspress or getform)
# getform_endpoint: 83b703c3-9e47-4df4-ac55-e24d7eb02abc
formspree_email: johndoe@gmail.com

# releases - widget can be (sidebar, modal or embed)
olvy_organization: devlopr
olvy_widget_type: sidebar

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug
  -
    scope:
      path: 'assets/**'
    values:
      sitemap: false

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-admin

# Jekyll Admin Config
jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  homepage: "posts"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

### Switching Deployment Strategy (in DEPLOY_STRATEGY) file change the key accordingly:
# none - For no default
# gh-pages - For Github Pages
# firebase - For Firebase Hosting

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - assets/bower_components/isotope-layout/README.md
  - assets/bower_components/icono/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-svg-core/README.md
  - assets/bower_components/ghosthunter/README.md
  - assets/bower_components/nanobar/README.md
  - assets/bower_components/lightgallery/demo/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-brands-svg-icons/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-solid-svg-icons/README.md
  - assets/bower_components/jquery-mousewheel/README.md
  - assets/bower_components/get-size/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome/README.md
  - assets/bower_components/jquery-mousewheel/ChangeLog/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-regular/README.md
  - assets/bower_components/desandro-matches-selector/README.md
  - assets/bower_components/ev-emitter/README.md
  - assets/bower_components/font-awesome/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-solid/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-webfonts/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-brands/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-common-types/README.md
  - assets/bower_components/ghosthunter/example/Index.html
  - assets/bower_components/lightgallery/test/lightgallery.html
  - assets/bower_components/masonry-layout/README.md
  - assets/bower_components/imagesloaded/README.md


destination: ./build
